name: Infra-module Validation Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: "."
        type: string
      deploy-pipeline:
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        if: steps.init.outcome == 'success'
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: TFLint - Setup
        if: steps.init.outcome == 'success'
        uses: terraform-linters/setup-tflint@v3
        
      - name: TFLint - Run 
        if: steps.init.outcome == 'success'
        id: tflint
        run: tflint --recursive
        continue-on-error: true

      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          skip_check: ${{ inputs.deploy-pipeline == false && 'CKV2_AWS_6,CKV_AWS_18,CKV2_AWS_62,CKV_AWS_144,CKV_AWS_145,CKV2_AWS_61,CKV_AWS_21,CKV_GCP_30,CKV_GCP_32,CKV_GCP_37,CKV_GCP_40,CKV_GCP_62,CKV_GCP_78' || '' }}
          directory: ${{ inputs.working-directory }}
          output_format: cli
          output_file_path: console

      - name: Check Terraform Job Status
        if: always()
        run: |
          if [[ "${{ steps.fmt.outcome }}" == "failure" || \
                "${{ steps.validate.outcome }}" == "failure" || \
                "${{ steps.tflint.outcome }}" == "failure" || \
                "${{ steps.checkov.outcome }}" == "failure" ]]; then
            echo "One or more Terraform validation steps failed"
            exit 1
          fi

  ansible-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ansible-lint (Formatting / Linting)
        id: ansible-lint
        uses: ansible/ansible-lint@main
        continue-on-error: true
        with:
          working_directory: ${{ inputs.working-directory }}
      
      - name: Run Vulnerability Scanner
        id: vulnerability-scan
        uses: j0rdan-m/ansible-vulnerability-scanner@v2.0.1
        continue-on-error: true
        with:
          artifact_path: ${{ inputs.working-directory }}
        
      - name: Check Ansible Job Status
        if: always()
        run: |
          if [[ "${{ steps.ansible-lint.outcome }}" == "failure" || \
                "${{ steps.vulnerability-scan.outcome }}" == "failure" ]]; then
            echo "One or more Ansible validation steps failed"
            exit 1
          fi
