name: Infra-module Validation Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: "."
        type: string

# version locking? redundant tests? e,g, do i need ansible-playbook syntax check with the ansible lintting?
# pin verisons 

# need to add directoy for actions

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        if: steps.init.outcome == 'success'
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: TFLint - Setup
        if: steps.init.outcome == 'success'
        uses: terraform-linters/setup-tflint@v3
        
      - name: TFLint - Run 
        if: steps.init.outcome == 'success'
        id: tflint
        run: tflint --recursive
        continue-on-error: true

      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          directory: ${{ inputs.working-directory }}
          output_format: cli
          output_file_path: console

      - name: Check Terraform Job Status
        if: always()
        run: |
          if [[ "${{ steps.fmt.outcome }}" == "failure" || \
                "${{ steps.validate.outcome }}" == "failure" || \
                "${{ steps.tflint.outcome }}" == "failure" || \
                "${{ steps.checkov.outcome }}" == "failure" ]]; then
            echo "One or more Terraform validation steps failed"
            exit 1
          fi

  ansible-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ansible-lint (Formatting / Linting)
        id: ansible-lint
        uses: ansible/ansible-lint@main
        continue-on-error: true
        with:
          #   args: ""
          #   setup_python: "true"
          working_directory: ${{ inputs.working-directory }}
        #   requirements_file: ""
      # https://github.com/marketplace/actions/run-ansible-lint
      

      - name: Run Vulnerability Scanner
        id: vulnerability-scan
        uses: j0rdan-m/ansible-vulnerability-scanner@v2.0.1
        continue-on-error: true
                # https://github.com/marketplace/actions/ansible-vulnerability-scanner ---- working dir

      - name: Check Ansible Job Status
        if: always()
        run: |
          if [[ "${{ steps.ansible-lint.outcome }}" == "failure" || \
                "${{ steps.vulnerability-scan.outcome }}" == "failure" ]]; then
            echo "One or more Ansible validation steps failed"
            exit 1
          fi
